name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Install a Python to run cibuildwheel itself
      - name: Set up Python for cibuildwheel
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) Install cibuildwheel (and auditwheel for Linux repair)
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.0.0b1 auditwheel

      # 4) Build wheels for *all* supported Pythons and platforms
      #    by running cibuildwheel from inside python/
      - name: Build wheels
        working-directory: python
        run: python -m cibuildwheel --output-dir ../wheelhouse

      # 5) Repair any manylinux wheels (this step is optional—
      #    cibuildwheel will auto-repair by default, but here’s how to do it manually)
      - name: Repair Linux wheels
        if: runner.os == 'Linux'
        run: |
          for whl in wheelhouse/*manylinux*.whl; do
            auditwheel repair "$whl" \
              --plat manylinux2014_x86_64 \
              -w wheelhouse/
          done

      # 6) Publish to PyPI (only when pushing a tag)
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          distributions: 'wheelhouse/*'
