name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python for cibuildwheel
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.0.0b1 auditwheel
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse python
        env:
          CIBW_ARCHS_LINUX: "x86_64"

      - name: Repair Linux wheels
        if: runner.os == 'Linux'
        run: |
          for whl in wheelhouse/*manylinux*.whl; do
            auditwheel repair "$whl" \
              --plat manylinux2014_x86_64 \
              -w wheelhouse/
          done

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          distributions: 'wheelhouse/*'
