name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and repair wheels
        uses: cibuildwheel/action@v2
        with:
          project-dir: python
          output-dir: wheelhouse
        env:
          CIBW_REPAIR_WHEEL: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          distributions: 'wheelhouse/*'
