# .github/workflows/build-wheels.yml
name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build all the wheels
        run: cibuildwheel --project-dir python --output-dir wheelhouse

      - name: Repair Linux wheels (manylinux)
        run: |
          pip install auditwheel
          for whl in wheelhouse/*linux_x86_64.whl; do
            auditwheel repair "$whl" --plat manylinux2014_x86_64 -w wheelhouse/
          done

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
